apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:yer-retb/app_use_argocd.git
  sshPrivateKey: |
    "key"
