Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
 
  config.vm.define "yer-retbS" do |master|
	master.vm.hostname = "yer-retbS"
	master.vm.network "private_network", ip: "192.168.56.110"
	master.vm.synced_folder ".", "/vagrant", disabled: false
	master.vm.provider "virtualbox" do |v|
		v.name = "yer-retbS"
	     	v.gui = false
	     	v.memory = "1024"
	     	v.cpus = 1
		end
	master.vm.provision "shell", path: "scripts/k3s_master.sh"
	end
 
end

#NAT
#Network
#Public Network


#VirtualBox: VirtualBox Shared Folders
#VMware: VMware Shared Folders
# NFS / SMB /  rsync

#curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 --node-ip 192.168.56.111 --token hakkache02" sh -s -
#curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip 192.168.56.110 --write-kubeconfig-mode 0644 --token hakkache02" sh -s -
