Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
 
  config.vm.define "yer-retbS" do |master|
	master.vm.hostname = "yer-retbS"
	master.vm.network "private_network", ip: "192.168.56.110"
	master.vm.synced_folder ".", "/vagrant", disabled: false
	master.vm.provider "virtualbox" do |v|
		v.name = "yer-retbS"
	     	v.gui = false
	     	v.memory = "1024"
	     	v.cpus = 1
		end
	master.vm.provision "shell", path: "scripts/k3s_master.sh"
	end
 
end
