Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.define "yer-retbS" do |server|
        server.vm.hostname = "yer-retbS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/server.sh"
    end

    config.vm.define "yer-retbSW" do |worker|
        worker.vm.hostname = "yer-retbSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        worker.vm.provision "shell", path: "scripts/worker.sh"
    end
end